#!/bin/sh
set -e

lb config noauto \
    --architecture amd64 \
    --distribution bookworm \
    --system live \
    --bootappend-live "boot=live components quiet splash" \
    --bootappend-install "auto=true priority=critical preseed/file=/cdrom/install/preseed.cfg quiet" \
    --iso-application "Beout_OS Installer" \
    --iso-publisher "Beout_OS Demo" \
    --iso-volume "BEOUT_OS_INSTALLER" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends false \
    --linux-packages "linux-image" \
    --linux-flavours "amd64" \
    --uefi-secure-boot disable \
    --debian-installer live \
    "${@}"
