#!/bin/bash
# Synchronizes SQLite configuration to the Debian OS network interfaces
set -e

DB_PATH="/var/lib/beout_os/config.db"
INTERFACES_FILE="/etc/network/interfaces.d/beout_os_interfaces"

# Helper to get config from sqlite
get_config() {
    sqlite3 "$DB_PATH" "SELECT value FROM config WHERE key='$1';" 2>/dev/null || echo ""
}

WAN_IP=$(get_config "network_WAN_ip")
WAN_NETMASK=$(get_config "network_WAN_netmask")
LAN_IP=$(get_config "network_LAN_ip")
LAN_NETMASK=$(get_config "network_LAN_netmask")
MGMT_IP=$(get_config "network_MGMT_ip")
MGMT_NETMASK=$(get_config "network_MGMT_netmask")

# Start generating the interfaces file
echo "# Generated by Beout_OS Configuration Engine" > "$INTERFACES_FILE"

# Assuming eth0 = WAN, eth1 = LAN, eth2 = MGMT for this demo appliance hardware
if [ -n "$WAN_IP" ]; then
    echo "auto eth0" >> "$INTERFACES_FILE"
    echo "iface eth0 inet static" >> "$INTERFACES_FILE"
    echo "    address $WAN_IP" >> "$INTERFACES_FILE"
    [ -n "$WAN_NETMASK" ] && echo "    netmask $WAN_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

if [ -n "$LAN_IP" ]; then
    echo "auto eth1" >> "$INTERFACES_FILE"
    echo "iface eth1 inet static" >> "$INTERFACES_FILE"
    echo "    address $LAN_IP" >> "$INTERFACES_FILE"
    [ -n "$LAN_NETMASK" ] && echo "    netmask $LAN_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

if [ -n "$MGMT_IP" ]; then
    echo "auto eth2" >> "$INTERFACES_FILE"
    echo "iface eth2 inet static" >> "$INTERFACES_FILE"
    echo "    address $MGMT_IP" >> "$INTERFACES_FILE"
    [ -n "$MGMT_NETMASK" ] && echo "    netmask $MGMT_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

# Reload networking to apply changes
# On Debian 12, 'systemctl restart networking' or 'ifreload -a' (if ifupdown2 is used)
systemctl restart networking || true
