#!/bin/bash
# Synchronizes SQLite configuration to the Debian OS network interfaces
set -e

DB_PATH="/var/lib/beout_os/config.db"
INTERFACES_FILE="/etc/network/interfaces.d/beout_os_interfaces"

# Helper to get config from sqlite
get_config() {
    sqlite3 "$DB_PATH" "SELECT value FROM config WHERE key='$1';" 2>/dev/null || echo ""
}

# Get IP and netmask configs
WAN_IP=$(get_config "network_WAN_ip")
WAN_NETMASK=$(get_config "network_WAN_netmask")
LAN_IP=$(get_config "network_LAN_ip")
LAN_NETMASK=$(get_config "network_LAN_netmask")
MGMT_IP=$(get_config "network_MGMT_ip")
MGMT_NETMASK=$(get_config "network_MGMT_netmask")

# Get dynamic interface assignments
WAN_IFACE=$(get_config "network_WAN_interface")
LAN_IFACE=$(get_config "network_LAN_interface")
MGMT_IFACE=$(get_config "network_MGMT_interface")

# 1. Reset /etc/network/interfaces to a clean, minimal state to prevent service start failures
cat <<EOF > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
EOF

# 2. Start generating the custom interfaces file
echo "# Generated by Beout_OS Configuration Engine" > "$INTERFACES_FILE"

if [ -n "$WAN_IFACE" ] && [ -n "$WAN_IP" ]; then
    echo "auto $WAN_IFACE" >> "$INTERFACES_FILE"
    echo "iface $WAN_IFACE inet static" >> "$INTERFACES_FILE"
    echo "    address $WAN_IP" >> "$INTERFACES_FILE"
    [ -n "$WAN_NETMASK" ] && echo "    netmask $WAN_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

if [ -n "$LAN_IFACE" ] && [ -n "$LAN_IP" ]; then
    echo "auto $LAN_IFACE" >> "$INTERFACES_FILE"
    echo "iface $LAN_IFACE inet static" >> "$INTERFACES_FILE"
    echo "    address $LAN_IP" >> "$INTERFACES_FILE"
    [ -n "$LAN_NETMASK" ] && echo "    netmask $LAN_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

if [ -n "$MGMT_IFACE" ] && [ -n "$MGMT_IP" ]; then
    echo "auto $MGMT_IFACE" >> "$INTERFACES_FILE"
    echo "iface $MGMT_IFACE inet static" >> "$INTERFACES_FILE"
    echo "    address $MGMT_IP" >> "$INTERFACES_FILE"
    [ -n "$MGMT_NETMASK" ] && echo "    netmask $MGMT_NETMASK" >> "$INTERFACES_FILE"
    echo "" >> "$INTERFACES_FILE"
fi

# Reload networking to apply changes
systemctl restart networking || true
